pipeline {
    agent {
        label ''
    }
    
    environment { 
        PROJECT_PATH = 'spring-boot-samples/spring-boot-sample-atmosphere'
    }
    
    stages {
        stage('Preparation') {
            environment { 
                REPO_BRANCH = 'develop'
                REPO_URL = 'https://github.com/davsanssg/jenkins2-course-spring-boot.git'
            }
            steps {
                echo 'Doing nothing in preparation..'
            }
        }
        
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    args '-v ${WORKSPACE}/${PROJECT_PATH}:/opt/maven -w /opt/maven'
                    reuseNode true
                }
            }    
            steps{
                dir(PROJECT_PATH){
                    sh 'printenv'
                    sh 'pwd'
                    sh 'ls'
                    echo 'Starting Build stage...'
                    echo 'Compiling, testing and building...'
                    sh label: '', script: 'mvn clean package'
                }
            }     

        }
        
        stage('Results'){
            steps{
                dir(PROJECT_PATH){
                    echo 'Starting Results stage...'
                    junit 'target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }      
            }
        }
        
    }

    post { 
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}