pipeline {
    agent any
    
    environment { 
        PROJECT_PATH = 'spring-boot-samples/spring-boot-sample-atmosphere'
    }
    
    stages {
        stage('Preparation') {
            environment { 
                REPO_BRANCH = 'develop'
                REPO_URL = 'https://github.com/davsanssg/jenkins2-course-spring-boot.git'
            }
            steps {
                echo 'Cleaning workspace..'
                cleanWs()
            }
        }
        
        stage('Build') {
            steps{
                echo 'Compiling, testing and building...'
                dir(PROJECT_PATH){
                    sh label: '', script: 'mvn clean package'   
                }
            }
        }
        
        stage('Results'){
            steps{
                dir(PROJECT_PATH){
                    junit 'target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        
    }
}